// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: companion

#ifndef UI_CALIBRATIONSCREEN_H
#define UI_CALIBRATIONSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_calibrationScreen
extern void ui_calibrationScreen_screen_init(void);
extern void ui_calibrationScreen_screen_destroy(void);
extern void ui_event_calibrationScreen(lv_event_t * e);
extern lv_obj_t * ui_calibrationScreen;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_gravityCalButton;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_forwardCalButton;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Label5;
extern void ui_event_Button6(lv_event_t * e);
extern lv_obj_t * ui_Button6;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

