// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: companion

#include "ui.h"

lv_obj_t * ui_calibrationScreen = NULL;
lv_obj_t * ui_Label1 = NULL;
lv_obj_t * ui_gravityCalButton = NULL;
lv_obj_t * ui_Label4 = NULL;
lv_obj_t * ui_forwardCalButton = NULL;
lv_obj_t * ui_Label2 = NULL;
lv_obj_t * ui_Label5 = NULL;
lv_obj_t * ui_Button6 = NULL;
// event funtions
void ui_event_calibrationScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        activity_event_handler(e);
    }
}

void ui_event_Button6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Screen1_screen_init);
    }
}

// build funtions

void ui_calibrationScreen_screen_init(void)
{
    ui_calibrationScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_calibrationScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label1 = lv_label_create(ui_calibrationScreen);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, -8);
    lv_obj_set_y(ui_Label1, -154);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "IMU Calibration");
    lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_gravityCalButton = lv_btn_create(ui_calibrationScreen);
    lv_obj_set_width(ui_gravityCalButton, 158);
    lv_obj_set_height(ui_gravityCalButton, 76);
    lv_obj_set_x(ui_gravityCalButton, -114);
    lv_obj_set_y(ui_gravityCalButton, 86);
    lv_obj_set_align(ui_gravityCalButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_gravityCalButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_gravityCalButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label4 = lv_label_create(ui_gravityCalButton);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "Gravity\nStationary");
    lv_obj_set_style_text_font(ui_Label4, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_forwardCalButton = lv_btn_create(ui_calibrationScreen);
    lv_obj_set_width(ui_forwardCalButton, 135);
    lv_obj_set_height(ui_forwardCalButton, 69);
    lv_obj_set_x(ui_forwardCalButton, 114);
    lv_obj_set_y(ui_forwardCalButton, 84);
    lv_obj_set_align(ui_forwardCalButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_forwardCalButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_forwardCalButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label2 = lv_label_create(ui_forwardCalButton);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "Forward \nDrive");
    lv_obj_set_style_text_font(ui_Label2, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label5 = lv_label_create(ui_calibrationScreen);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, -11);
    lv_obj_set_y(ui_Label5, -38);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "Calibration status info");
    lv_obj_set_style_text_font(ui_Label5, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button6 = lv_btn_create(ui_calibrationScreen);
    lv_obj_set_width(ui_Button6, 444);
    lv_obj_set_height(ui_Button6, 208);
    lv_obj_set_x(ui_Button6, 0);
    lv_obj_set_y(ui_Button6, -85);
    lv_obj_set_align(ui_Button6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button6, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Button6, ui_event_Button6, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_calibrationScreen, ui_event_calibrationScreen, LV_EVENT_ALL, NULL);

}

void ui_calibrationScreen_screen_destroy(void)
{
    if(ui_calibrationScreen) lv_obj_del(ui_calibrationScreen);

    // NULL screen variables
    ui_calibrationScreen = NULL;
    ui_Label1 = NULL;
    ui_gravityCalButton = NULL;
    ui_Label4 = NULL;
    ui_forwardCalButton = NULL;
    ui_Label2 = NULL;
    ui_Label5 = NULL;
    ui_Button6 = NULL;

}
