// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: companion

#include "ui.h"

lv_obj_t * ui_InclinometerScreen = NULL;
lv_obj_t * ui_PitchCarImage = NULL;
lv_obj_t * ui_RollCarImage = NULL;
lv_obj_t * ui_PitchLabel = NULL;
lv_obj_t * ui_RollLabel = NULL;
lv_obj_t * ui_labelMotionIcon3 = NULL;
lv_obj_t * ui_Button4 = NULL;
lv_obj_t * ui_Button5 = NULL;
// event funtions
void ui_event_Button4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        activity_event_handler(e);
    }
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Screen1_screen_init);
    }
}

void ui_event_Button5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        activity_event_handler(e);
    }
    if(event_code == LV_EVENT_CLICKED) {
        buttonGmeter_event_handler(e);
    }
}

// build funtions

void ui_InclinometerScreen_screen_init(void)
{
    ui_InclinometerScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_InclinometerScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_InclinometerScreen, lv_color_hex(0x101C20), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_InclinometerScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PitchCarImage = lv_img_create(ui_InclinometerScreen);
    lv_img_set_src(ui_PitchCarImage, &ui_img_1435680676);
    lv_obj_set_width(ui_PitchCarImage, LV_SIZE_CONTENT);   /// 200
    lv_obj_set_height(ui_PitchCarImage, LV_SIZE_CONTENT);    /// 95
    lv_obj_set_x(ui_PitchCarImage, -86);
    lv_obj_set_y(ui_PitchCarImage, -65);
    lv_obj_set_align(ui_PitchCarImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PitchCarImage, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_PitchCarImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_RollCarImage = lv_img_create(ui_InclinometerScreen);
    lv_img_set_src(ui_RollCarImage, &ui_img_2121104240);
    lv_obj_set_width(ui_RollCarImage, LV_SIZE_CONTENT);   /// 226
    lv_obj_set_height(ui_RollCarImage, LV_SIZE_CONTENT);    /// 200
    lv_obj_set_x(ui_RollCarImage, -85);
    lv_obj_set_y(ui_RollCarImage, 87);
    lv_obj_set_align(ui_RollCarImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_RollCarImage, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_RollCarImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_RollCarImage, 140);

    ui_PitchLabel = lv_label_create(ui_InclinometerScreen);
    lv_obj_set_width(ui_PitchLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PitchLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PitchLabel, 100);
    lv_obj_set_y(ui_PitchLabel, -58);
    lv_obj_set_align(ui_PitchLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PitchLabel, "0.0°");
    lv_obj_set_style_text_font(ui_PitchLabel, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RollLabel = lv_label_create(ui_InclinometerScreen);
    lv_obj_set_width(ui_RollLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RollLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RollLabel, 100);
    lv_obj_set_y(ui_RollLabel, 94);
    lv_obj_set_align(ui_RollLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RollLabel, "0.0°");
    lv_obj_set_style_text_font(ui_RollLabel, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelMotionIcon3 = lv_label_create(ui_InclinometerScreen);
    lv_obj_set_width(ui_labelMotionIcon3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelMotionIcon3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelMotionIcon3, 190);
    lv_obj_set_y(ui_labelMotionIcon3, -155);
    lv_obj_set_align(ui_labelMotionIcon3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelMotionIcon3, "");
    lv_obj_set_style_text_font(ui_labelMotionIcon3, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button4 = lv_btn_create(ui_InclinometerScreen);
    lv_obj_set_width(ui_Button4, 198);
    lv_obj_set_height(ui_Button4, 365);
    lv_obj_set_x(ui_Button4, 118);
    lv_obj_set_y(ui_Button4, -3);
    lv_obj_set_align(ui_Button4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button5 = lv_btn_create(ui_InclinometerScreen);
    lv_obj_set_width(ui_Button5, 198);
    lv_obj_set_height(ui_Button5, 365);
    lv_obj_set_x(ui_Button5, -122);
    lv_obj_set_y(ui_Button5, -3);
    lv_obj_set_align(ui_Button5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Button4, ui_event_Button4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button5, ui_event_Button5, LV_EVENT_ALL, NULL);

}

void ui_InclinometerScreen_screen_destroy(void)
{
    if(ui_InclinometerScreen) lv_obj_del(ui_InclinometerScreen);

    // NULL screen variables
    ui_InclinometerScreen = NULL;
    ui_PitchCarImage = NULL;
    ui_RollCarImage = NULL;
    ui_PitchLabel = NULL;
    ui_RollLabel = NULL;
    ui_labelMotionIcon3 = NULL;
    ui_Button4 = NULL;
    ui_Button5 = NULL;

}
