// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: companion

#ifndef UI_INCLINOMETERSCREEN_H
#define UI_INCLINOMETERSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_InclinometerScreen
extern void ui_InclinometerScreen_screen_init(void);
extern void ui_InclinometerScreen_screen_destroy(void);
extern void ui_event_InclinometerScreen(lv_event_t * e);
extern lv_obj_t * ui_InclinometerScreen;
extern lv_obj_t * ui_PitchCarImage;
extern lv_obj_t * ui_RollCarImage;
extern lv_obj_t * ui_PitchLabel;
extern lv_obj_t * ui_RollLabel;
extern lv_obj_t * ui_labelMotionIcon3;
extern void ui_event_Button4(lv_event_t * e);
extern lv_obj_t * ui_Button4;
extern void ui_event_Button5(lv_event_t * e);
extern lv_obj_t * ui_Button5;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

