// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: companion_land_sdcard

#include "ui.h"

lv_obj_t * ui_Screen4 = NULL;
lv_obj_t * ui_Image4 = NULL;
lv_obj_t * ui_Image5 = NULL;
// event funtions

// build funtions

void ui_Screen4_screen_init(void)
{
    ui_Screen4 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen4, lv_color_hex(0x101C20), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image4 = lv_img_create(ui_Screen4);
    lv_img_set_src(ui_Image4, &ui_img_1435680676);
    lv_obj_set_width(ui_Image4, LV_SIZE_CONTENT);   /// 200
    lv_obj_set_height(ui_Image4, LV_SIZE_CONTENT);    /// 95
    lv_obj_set_x(ui_Image4, -79);
    lv_obj_set_y(ui_Image4, -70);
    lv_obj_set_align(ui_Image4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image5 = lv_img_create(ui_Screen4);
    lv_img_set_src(ui_Image5, &ui_img_2121104240);
    lv_obj_set_width(ui_Image5, LV_SIZE_CONTENT);   /// 226
    lv_obj_set_height(ui_Image5, LV_SIZE_CONTENT);    /// 200
    lv_obj_set_x(ui_Image5, -86);
    lv_obj_set_y(ui_Image5, 78);
    lv_obj_set_align(ui_Image5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image5, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image5, 140);

}

void ui_Screen4_screen_destroy(void)
{
    if(ui_Screen4) lv_obj_del(ui_Screen4);

    // NULL screen variables
    ui_Screen4 = NULL;
    ui_Image4 = NULL;
    ui_Image5 = NULL;

}
