"use strict";
// Execute actual main-task observer bodies; no firmware compilation.
const fs=require('fs'),vm=require('vm'),assert=require('assert/strict');
const read=p=>fs.readFileSync(p,'utf8').replace(/\r/g,'');
const source=read('src/diagnostics/diagnostics_mqtt_service.cpp');
const strip=s=>s.replace(/\/\/[^\n]*|\/\*[\s\S]*?\*\//g,'');
function body(s,sig){s=strip(s);let p=s.indexOf(sig);assert(p>=0,sig);p=s.indexOf('{',p);let start=++p,d=1;while(d){if(s[p]==='{')d++;if(s[p]==='}')d--;p++;}return s.slice(start,p-1);}
function adapt(s){return s.replace(/^#.*$/gm,'').replace(/\(unsigned long long\)|\(unsigned long\)/g,'').replace(/uint(?:8|32)_t\(([^)]+)\)/g,'($1)').replace(/const (?:uint\d+_t|auto&) /g,'const ').replace(/auto& /g,'const ').replace('for(auto& m:metrics)','for(const m of metrics)').replace('for(const m:metrics)','for(const m of metrics)').replace('char fields[456];',"let fields='';").replace('snprintf(fields,sizeof(fields),','fields=format(').replace(/diag::mainBreadcrumb\(\)/g,'breadcrumb()').replace(/diag::record/g,'record');}
function context(){const c={t:0,phase:1,metrics:Array.from({length:3},()=>({gap:0,cost:0,count:0,over:0,depth:0,entered:0,last:0})),active:false,attempt:0,contexts:0,spanMs:0,started:0,span:'none',UINT32_MAX:4294967295,records:[]};c.now=()=>c.t;c.breadcrumb=()=>({phase:c.phase});c.record=(event,fields)=>c.records.push({event,fields});c.format=(fmt,...values)=>fmt.replace(/%llu|%lu|%s/g,()=>String(values.shift()));vm.createContext(c);
 for(const [sig,name,args] of [['uint32_t bounded(','bounded','value'],['void context(','context',''],['void gap(','gap','m,at'],['void cost(','cost','m,at'],['void begin(','begin','id,requestedMs'],['void enter(','enter','service'],['void leave(','leave','service'],['void block(','block','name,start,end'],['void finish(','finish','id']])vm.runInContext(`function ${name}(${args}){${adapt(body(source,sig))}}`,c);
 return c;}
let count=0;function test(name,fn){fn();count++;console.log('PASS '+name);}
test('idle observers emit nothing and first interval excludes pre-attempt history',()=>{const c=context();c.enter(0);c.t=900;c.leave(0);c.t=1000;c.begin(1,1000);c.t=1010;c.enter(0);c.t=1012;c.leave(0);c.t=1020;c.finish(1);assert.equal(c.metrics[0].gap,10);assert.equal(c.metrics[0].cost,2);assert.equal(c.records.length,1);});
test('UI and IMU intervals, call costs and strict over100 counts are independent',()=>{const c=context();c.begin(1,0);c.t=100;c.enter(0);c.t=105;c.leave(0);c.t=201;c.enter(0);c.t=211;c.leave(0);c.finish(1);assert.equal(c.metrics[0].gap,101);assert.equal(c.metrics[0].over,1);assert.equal(c.metrics[0].count,2);assert.equal(c.metrics[0].cost,10);assert.equal(c.metrics[1].gap,211);assert.equal(c.metrics[1].count,0);assert.equal(c.metrics[1].over,1);});
test('attempt started inside a loop clips the pre-request cost and includes adoption tail',()=>{const c=context();c.enter(2);c.t=300;c.begin(1,300);c.t=320;c.leave(2);c.t=350;c.enter(2);c.t=400;c.finish(1);assert.equal(c.metrics[2].cost,50);assert.equal(c.metrics[2].count,2);assert.equal(c.metrics[2].gap,50);c.t=900;c.leave(2);assert.equal(c.metrics[2].cost,50);});
test('nested service calls preserve outer cost without double counting',()=>{const c=context();c.begin(1,0);c.enter(0);c.t=10;c.enter(0);c.t=20;c.leave(0);c.t=30;c.leave(0);c.finish(1);assert.equal(c.metrics[0].count,1);assert.equal(c.metrics[0].cost,30);assert.equal(c.metrics[0].depth,0);});
test('stale or repeated finish cannot close another attempt or emit twice',()=>{const c=context();c.begin(2,0);c.t=10;c.finish(1);assert(c.active);assert.equal(c.records.length,0);c.finish(2);c.finish(2);assert.equal(c.records.length,1);});
test('late completion retains long stall, saturates safely and resets next attempt',()=>{const c=context();c.begin(1,0);c.t=4294967395;c.finish(1);assert.equal(c.metrics[0].gap,4294967295);c.begin(2,c.t);c.t+=5;c.finish(2);assert.equal(c.metrics[0].gap,5);assert.equal(c.metrics[0].over,0);});
test('main span attribution clips overlap, retains longest and is not worker timing',()=>{const c=context();c.begin(1,100);c.block('old',0,99);c.block('image_https',0,300);c.block('nested',210,220);assert.equal(c.span,'image_https');assert.equal(c.spanMs,200);c.t=400;c.finish(1);assert(c.records[0].fields.includes('span=image_https span_ms=200'));});
test('phase context mask captures overlapping contexts without per-call records',()=>{const c=context();c.phase=2;c.begin(1,0);c.phase=15;c.enter(0);c.phase=1;c.leave(0);assert.equal(c.records.length,0);c.finish(1);assert.equal(c.contexts,(1<<2)|(1<<15)|(1<<1));});
test('worst-width SERVICE and MEM records fit the 456-byte field limit',()=>{const fmt=source.match(/snprintf\(fields,sizeof\(fields\),"([^"]+)"/)[1];const worst=fmt.replace(/%llu/g,'18446744073709551615').replace(/%lu/g,'4294967295').replace(/%s/g,'serial_commands');assert(worst.length<456,worst.length);const net=read('src/net/net_module.cpp');const mem=net.match(/"MQTT_CONNECT_MEM","([^"]+)"/)[1].replace(/%lu|%u/g,'4294967295');assert(mem.length<456);assert(mem.includes('dma_largest_min='));});
test('every authored LVGL call and IMU entry is wrapped; legacy calls remain',()=>{for(const file of ['companion.ino','src/image/image_fetcher.cpp','src/video/video_stream.cpp']){const s=read(file);assert.equal((s.match(/lv_timer_handler\(\);/g)||[]).length,(s.match(/diagmqtt::Call service\(diagmqtt::Service::Ui\); lv_timer_handler\(\);/g)||[]).length,file);}const imu=read('src/imu/imu_module.cpp');assert(imu.includes('void updateImuData() {\n  diagmqtt::Call service(diagmqtt::Service::Imu);'));const op=read('src/diagnostics/diagnostics_operation.cpp');assert(op.includes('diagmqtt::enter(diagmqtt::Service::Loop)'));assert(op.includes('diagmqtt::leave(diagmqtt::Service::Loop)'));assert(op.includes('diagmqtt::block(name,start,end)'));});
test('accepted request starts window and common result path closes after READY adoption',()=>{const net=read('src/net/net_module.cpp');assert(net.indexOf('mqttowner::request(attemptId+1')<net.indexOf('diagmqtt::begin(attemptId'));const result=body(net,'if(mqttowner::takeResult(result))');assert(result.lastIndexOf('diagmqtt::finish(result.id)')>result.indexOf('mqttowner::acknowledgeReady'));assert.equal((result.match(/diagmqtt::finish/g)||[]).length,1);assert(!read('src/net/net_worker.cpp').includes('diagmqtt::'));});
test('observer has no network, allocations, tasks or per-service record emissions',()=>{assert(!/xTaskCreate|malloc\(|new |SD_MMC|WiFi\.|USBSerial|Preferences|vTaskDelay/.test(strip(source)));for(const sig of ['void enter(','void leave(','void block('])assert(!body(source,sig).includes('record('));assert.equal((source.match(/diag::record\(/g)||[]).length,1);});
test('normal health snapshots and records carry phase age lease and bounded backoff',()=>{
 const net=read('src/net/net_module.cpp'),health=body(net,'void netMqttHealth(');
 for(const field of ['mqttWorkerPhase','mqttWorkerId','mqttWorkerAge','mqttBackoffMs','mqttLease'])assert(health.includes(field));
 assert(read('companion.ino').includes('netMqttHealth(health)'));
 const sd=read('src/diagnostics/sd_diagnostics.cpp');const part=sd.slice(sd.indexOf('"snapshot_valid=%u snapshot_age_ms='),sd.indexOf('"NET_HEALTH", fields'));
 const fmt=[...part.matchAll(/"([^"\n]*)"/g)].map(m=>m[1]).join('');
 const worst=fmt.replace(/%llu|%lld/g,'18446744073709551615').replace(/%lu|%u|%d/g,'4294967295').replace(/%s/g,'tcp_setup');
 assert(worst.length<704,worst.length);assert(fmt.includes('worker_phase=%s'));assert(net.includes('backoff_ms=%lu'));
});
test('backoff reports only remaining rate-limit time, including millis rollover',()=>{
 const net=read('src/net/net_module.cpp');let s=body(net,'uint32_t retryRemaining(').replace('const uint32_t elapsed=millis()-lastMqttAttempt;','const elapsed=(millis()-lastMqttAttempt)>>>0;');
 const remaining=new Function('millis','lastMqttAttempt','MQTT_RECONNECT_INTERVAL',s);
 for(const [at,start,want] of [[1000,1000,15000],[6000,1000,10000],[16000,1000,0],[17000,1000,0],[100,4294967196,14800]])assert.equal(remaining(()=>at,start,15000),want);
});
console.log(`${count} MQTT service checks passed; source simulations only, no firmware build.`);
